import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Mercy Dev Studio | Fullstack Developer & Digital Agency',
  description:
    'Professional fullstack developer based in Lagos. I build fast, beautiful web experiences — websites, apps, and brand design that convert.',
  keywords: ['fullstack developer', 'web developer Nigeria', 'Next.js developer', 'Lagos developer'],
  openGraph: {
    title: 'Mercy Dev Studio',
    description: 'I build things people love to use.',
    type: 'website',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
